### ISSUE TITLE
"White Screen"

### ISSUE THREAD

**Issue by fwolfers** [ridereceipts/ridereceipts#10]
First startup of the app and the app only shows a "white screen"

![bildschirmfoto 2018-07-16 um 08 51 07](https://user-images.githubusercontent.com/5314162/42745900-788374e2-88d5-11e8-8ace-028acdc39d98.png)

I'm getting this on 10.11.6 - MacBook Pro (Retina, 13-inch, Early 2015).
Chromium is already installed.
Thanks in advance for your help

**Comment by mrgodhani** [comment]
@fwolfers Thanks I will look into it. Also is this latest version 1.5.2?

**Comment by mrgodhani** [comment]
@fwolfers Thanks fixed https://github.com/ridereceipts/ridereceipts/releases/tag/v1.5.4

**Comment by fwolfers** [comment]
Thanks!
