### ISSUE TITLE
v1.5.5 still asking to download Chromium

### ISSUE THREAD

**Issue by james2307** [ridereceipts/ridereceipts#11]
Hi, I had installed the v1.5.4 first and it got stuck on the loading screen as described in [this](https://github.com/ridereceipts/ridereceipts/issues/8) issue.

![image](https://user-images.githubusercontent.com/37951028/43307151-16899018-919b-11e8-84aa-79f9394993e7.png)

As it was stuck due to chromium, I uninstalled the v1.5.4 and installed the v1.4.1 in which I could separately download chromium and place it on the desktop. Now I was able to pass through that loading screen and was asked to enter my Uber email. After I did, it kept on showing me this error message: "Ride Receipts failed to verify your account. Please try again.". I am sure that email I entered was correct.

Then I uninstalled the v1.4.1 and re-installed the v1.5.4  and it showed me this error after launching and clicking on Uber: "It seems like you don't have Chromium installed. Please download it from here. Place the file on your desktop and unzip it.". It shouldn't show this error on v1.5.4. Isn't it?

And if I place the unzipped chromium file on the desktop, and restart the app and go through the steps, the app sometimes get stuck or sometimes shows me the error message: "Ride Receipts failed to verify your account. Please try again.".

I saw that you released v1.5.5 which fixes the chromium loading screen error so I unsintalled v1.5.4 and installed v1.5.5. Now when I launch the app and click to get the Uber receipts, it shows me this error message: "It seems like you don't have Chromium installed. Please download it from here. Place the file on your desktop and unzip it.". And even if I place the unzipped file, the error remains the same.

**Comment by BeSLN** [comment]
Exact same problem.
If I put the folder on my desktop or If I directly put everything on the desktop - dll, exe... - I have the same error message.
![image](https://user-images.githubusercontent.com/20780079/43314540-8890be78-9193-11e8-9b70-026234cf7276.png)

**Comment by mrgodhani** [comment]
Yes still aware about this. Found it after release. I am working on it.

**Comment by mrgodhani** [comment]
https://github.com/ridereceipts/ridereceipts/releases/tag/v1.5.6 Fixed. Note that fix has also increased size of the app. For now is a hack solution

**Comment by james2307** [comment]
Thanks a lot. It worked.
