### ISSUE TITLE
No progress when downloading receipts. Doesn't download.

### ISSUE THREAD

**Issue by nunocordeiro** [ridereceipts/ridereceipts#18]
**Describe the bug**
No progress when downloading receipts.

**To Reproduce**
1. Installling. Please wait... Then I choose Uber and log into the email
2a. System says I'll need an app to open the file type (org.ridereceipts.ridereceipts)
2b. This is unexpected and happens in windows when you try to open a file with an extension not registered to an application. I close this window and application proceeds. I then choose "last 3 months" and "next".
3. The next window says "You have 13 trips. Pour yourself a drink and relax. We got this."
4. The progress bar never moves forward.

**Screenshots**
Which screenshots would help? Of the app or the Uber emails?

**Desktop (please complete the following information):**
 - OS: Windows 10 build 17134
 - Ridereceipts v1.7.1

**Comment by agreen** [comment]
I get nearly the same issue with the "app to open" on both on Uber and Lyft. For Uber it does create a RideReceipts/(emailadress)/undefined/2018 folder and populates it with one receipt. For Lyft it creates a RideReceipts/(emailaddress)/Lyft/2018 folder and populates it with one receipt as well. Additionally, I no longer can locate how to enter debug mode to try and see where the breakdown is.

**Comment by mrgodhani** [comment]
I will look into this when I am back from vacation

**Comment by mrgodhani** [comment]
https://github.com/ridereceipts/ridereceipts/releases/tag/v1.7.2 Fixed
