### ISSUE TITLE
Nothing is happening when i click on next to download invoices

### ISSUE THREAD

**Issue by daweedco** [ridereceipts/ridereceipts#19]
**Describe the bug**
Doesn't work at all

**To Reproduce**
After launching app , i click on uber, then i log in with gmail , and when i click on next nothing is happening

**Screenshots**
<img width="970" alt="capture d ecran 2019-01-25 a 14 39 35" src="https://user-images.githubusercontent.com/6706000/51749223-124e5580-20af-11e9-89b1-14228385b43a.png">

**Desktop (please complete the following information):**
 - OS: MAC OS 10.14.1
 - Browser Chrome
 - Version 71

**Comment by mrgodhani** [comment]
@daweedco Can I please know which country you from? Because at moment there is existing issue with French translated email not supported

**Comment by daweedco** [comment]
Hi , thanks for the fast answer , yes I am , is it possible to not translate them ?

**Comment by mrgodhani** [comment]
@daweedco For that I would need sample uber email in french

**Comment by daweedco** [comment]
Ok i sent it on your email

**Comment by mrgodhani** [comment]
@daweedco Thanks will look into fixing it

**Comment by mrgodhani** [comment]
@daweedco Try it out https://github.com/ridereceipts/ridereceipts/releases/tag/v1.7.3 . You can download new release or you should get an update

**Comment by daweedco** [comment]
@mrgodhani Perfect it's working great thank you so much
