### ISSUE TITLE
Uber ride cancellation receipts go in folder named undefined

### ISSUE THREAD

**Issue by checkaayush** [ridereceipts/ridereceipts#20]
**Describe the bug**
Uber ride cancellation receipts come in a folder named `undefined` and name of pdf files also starts with undefined.

**To Reproduce**
1. Choose Uber
2. Sign in to your Gmail account
3. Download receipts for any length of time involving ride cancellations
4. See folder named `undefined` having cancellation receipts.

**Expected behavior**
A folder called `Cancellations` and file names starting with `Uber` should be there.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS Mojave
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] 73.0.3683.86

**Comment by mrgodhani** [comment]
@checkaayush can you provide me with sample cancelled uber receipt? You can email us at hello@ridereceipts.io

**Comment by checkaayush** [comment]
@mrgodhani Sure, have forwarded an email regarding the same at hello@ridereceipts.io.

**Comment by mrgodhani** [comment]
@checkaayush Thanks! Will look into it

**Comment by mrgodhani** [comment]
Closing this, it is fixed in v1.8.3
