### ISSUE TITLE
No selection of business/personal account

### ISSUE THREAD

**Issue by ChipWolf** [ridereceipts/ridereceipts#26]
**Describe the bug**
If a business account is present, it appears to take priority. Ride Reciepts interacts only with the business account and retrieves data from rides booked using the business account only.

It is a requirement for business accounts to use a personal account for login.

There is no selection of business or personal account during the receipt generation flow.

**To Reproduce**
1. Create an Uber for Business account using your existing Uber user profile
2. Take a ride using the Business profile on the Uber app.
3. Attempt to use Ride Reciepts to download reciepts for rides taken using your Personal profile.

**Expected behavior**
The ability to switch between the personal and business accounts.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: PRO 1.2.18

**Comment by mrgodhani** [comment]
@ChipWolf Thanks for the detail info. We will look into this
