### ISSUE TITLE
Getting Puppeteer working in electron-vue?

### ISSUE THREAD

**Issue by mvaneijgen** [ridereceipts/ridereceipts#28]
Hi I'm in to process of building a Electron app that lets you take screenshots of a site based on multiple screen sizes. The interface is coming along nicely and I do also already have the node/puppeteer script that running great, my problem now is how to get Puppeteer running within Electron (-vue).

I came across [your post](https://forum.vuejs.org/t/simple-automation-app-to-download-invoices-using-vue-js-electron-and-puppeteer/23189) mentioning Electron/Vue/Puppeteer and I was browsing your code to see how you've done it, but couldn't find anything. Could you maybe shine a light on how to invoke a node/puppeteer script from within electron-vue?

[Here is my Puppeteer script](https://github.com/mvaneijgen/docker-screenshot-sitemap/tree/master/code) (which is wrapped in a docker container, but can off course be ran stand alone)

[And here is my Electron app](https://github.com/mvaneijgen/screenshot-generator-app) build with Electron-vue.

**Comment by mrgodhani** [comment]
@mvaneijgen Ride Receipts at moment does not use Puppeteer anymore. We started with the puppeteer approach at the beginning. The way we integrated is using a puppeteer library but linking with the Chrome browser app installed in the system. We did not package electron with chrome that puppeteer includes.

**Comment by mvaneijgen** [comment]
I see. Is there still a version/commit of the code where puppeteer was included? I would love to see how you've did it. 

I my self are looking in to Node child processes at the moment to run puppeteer from there and then somehow get the users local chrome instance. 

If not just close this issue and I thank you for your response.

**Comment by mvaneijgen** [comment]
My app is done, [Screenshot Generator](https://github.com/mvaneijgen/screenshot-generator-app). 

Really happy how it functions, the only slight problem is that it doesn't work... I have a [Generate button compontent](https://github.com/mvaneijgen/screenshot-generator-app/blob/master/src/renderer/components/Start/Generate.vue) form which I try to launch a [puppeteer.js script](https://github.com/mvaneijgen/screenshot-generator-app/blob/master/src/renderer/plugins/puppeteer.js), but I just don't know how to invoke it.

If you have any pointers on how to get it working, please let me know, otherwise just close the issue. 

[![Screenshot Generator App Preview](https://i.imgur.com/pTSFKqk.png)](https://github.com/mvaneijgen/screenshot-generator-app)
