### ISSUE TITLE
What all do you need to do to get puppeteer to work with electron?

### ISSUE THREAD

**Issue by jmoseman01** [ridereceipts/ridereceipts#9]
I'm an angular guy but I was having problems getting puppeteer to work with electron. What all do you need to do to get puppeteer to work with electron?

**Comment by mrgodhani** [comment]
@jmoseman01 

In this app I am downloading Chromium using puppeteer library at first run using BrowserFetcher. So it is not running on electron's chromium. But it opens up chromium browser in background.  Refer: https://github.com/ridereceipts/ridereceipts/blob/master/src/renderer/services/puppeteer_download.js

**Comment by mrgodhani** [comment]
Also note that you can't codesign chromium browser while packaging hence it has to be outside electron.
